"""Stay archetypes and the words used to describe them. All text here is original demo copy."""

from dataclasses import dataclass


@dataclass(frozen=True)
class Archetype:
    property_type: str
    place_type: str
    category: str
    themes: tuple[str, ...]  # photo pools in the order they are used (first = cover)
    price: tuple[int, int]  # rupees per night
    guests: tuple[int, int]
    bedrooms: tuple[int, int]
    nouns: tuple[str, ...]
    features: tuple[str, ...]
    must: tuple[str, ...]  # amenity keys every such stay has
    may: tuple[str, ...]  # amenity keys picked from at random
    opener: str


ARCHETYPES: dict[str, Archetype] = {
    "beach_villa": Archetype(
        "villa",
        "entire",
        "beachfront",
        ("beach", "pool", "interior"),
        (9000, 38000),
        (4, 10),
        (2, 5),
        ("Beach Villa", "Palm Grove Villa", "Sunset Bungalow", "Coastal Retreat"),
        ("with private pool", "steps from the sand", "with sea views", "with a garden courtyard"),
        ("wifi", "kitchen", "ac", "pool", "beach_access", "hot_water"),
        ("free_parking", "bbq_grill", "balcony", "washer", "tv", "garden", "breakfast"),
        "A bright, airy villa built for long lazy days by the sea.",
    ),
    "beach_cottage": Archetype(
        "cottage",
        "entire",
        "tropical",
        ("beach", "cabin", "interior"),
        (3500, 9000),
        (2, 4),
        (1, 2),
        ("Beach Cottage", "Palm Hut", "Seaside Cottage", "Coconut Grove Cottage"),
        ("with a sit-out", "near the water", "with a hammock deck", "in a coconut grove"),
        ("wifi", "hot_water", "beach_access"),
        ("ac", "balcony", "breakfast", "garden", "bonfire", "tv"),
        "A simple, breezy cottage where the sound of the waves does the talking.",
    ),
    "design_loft": Archetype(
        "flat",
        "entire",
        "design",
        ("city", "interior", "pool"),
        (4500, 14000),
        (2, 4),
        (1, 2),
        ("Design Loft", "Studio Apartment", "Artist's Loft", "Sky Apartment"),
        ("with a workspace", "with city views", "in a restored building", "with a rooftop terrace"),
        ("wifi", "kitchen", "ac", "workspace", "hot_water"),
        ("washer", "tv", "balcony", "gym", "iron", "free_parking"),
        "A stylish, light-filled apartment with local art on the walls.",
    ),
    "city_apartment": Archetype(
        "flat",
        "entire",
        "design",
        ("city", "interior", "pool"),
        (3500, 12000),
        (2, 5),
        (1, 3),
        ("City Apartment", "Skyline Flat", "Serviced Apartment", "Urban Retreat"),
        ("near the metro", "with a balcony", "with fast wifi", "in a quiet lane"),
        ("wifi", "kitchen", "ac", "hot_water", "workspace"),
        ("washer", "tv", "gym", "free_parking", "iron", "balcony", "hair_dryer"),
        "A comfortable apartment that makes a busy city feel manageable.",
    ),
    "hill_cottage": Archetype(
        "cottage",
        "entire",
        "amazing_views",
        ("hills", "cabin", "interior"),
        (3000, 9500),
        (2, 6),
        (1, 3),
        ("Hill Cottage", "Valley View Cottage", "Mountain Hideaway", "Pine Ridge Cottage"),
        ("with valley views", "with a fireplace", "with a sunny deck", "surrounded by orchards"),
        ("wifi", "heating", "hot_water", "mountain_view"),
        ("kitchen", "bonfire", "balcony", "free_parking", "garden", "tv", "breakfast"),
        "A warm, wood-and-stone cottage that makes mountain evenings something to look forward to.",
    ),
    "cabin_stay": Archetype(
        "cabin",
        "entire",
        "cabins",
        ("cabin", "hills", "interior"),
        (2500, 7500),
        (2, 4),
        (1, 2),
        ("Wooden Cabin", "Forest Cabin", "A-Frame Cabin", "Riverside Cabin"),
        ("in the woods", "with a wood stove", "by the stream", "with a private deck"),
        ("wifi", "heating", "hot_water"),
        ("bonfire", "mountain_view", "garden", "balcony", "bbq_grill", "kitchen"),
        "A snug cabin for people who like their mornings quiet and their evenings by a fire.",
    ),
    "treehouse": Archetype(
        "treehouse",
        "entire",
        "treehouses",
        ("cabin", "estate", "hills"),
        (4500, 11000),
        (2, 3),
        (1, 1),
        ("Treehouse", "Canopy Nest", "Forest Treehouse", "Skyview Treehouse"),
        (
            "above the canopy",
            "with a wraparound deck",
            "among the treetops",
            "with a rope-bridge entrance",
        ),
        ("wifi", "hot_water", "garden_view"),
        ("breakfast", "balcony", "bonfire", "mountain_view"),
        "A treehouse that sits in the branches and feels a long way from everything.",
    ),
    "colonial_house": Archetype(
        "house",
        "entire",
        "countryside",
        ("hills", "interior", "estate"),
        (4500, 14000),
        (4, 8),
        (2, 4),
        ("Colonial Bungalow", "Hill Station Manor", "Old Raj Cottage", "Heritage Bungalow"),
        ("with a sunlit veranda", "with a rose garden", "with a fireplace", "built in the 1920s"),
        ("wifi", "heating", "hot_water", "garden"),
        ("kitchen", "free_parking", "breakfast", "mountain_view", "tv", "bonfire"),
        "A characterful old bungalow with high ceilings, a wide veranda and a well-kept garden.",
    ),
    "ladakh_guesthouse": Archetype(
        "guest_house",
        "private_room",
        "top_of_the_world",
        ("ladakh", "interior", "hills"),
        (2200, 7500),
        (2, 4),
        (1, 2),
        (
            "Mountain Guesthouse",
            "Himalayan Homestay",
            "Apricot Orchard Guesthouse",
            "Stupa View Room",
        ),
        (
            "with mountain views",
            "in an apricot orchard",
            "with home-cooked meals",
            "run by a local family",
        ),
        ("wifi", "heating", "hot_water", "mountain_view"),
        ("breakfast", "garden", "balcony", "free_parking"),
        "A family-run guesthouse with butter tea, home cooking and some of the clearest skies in India.",
    ),
    "desert_camp": Archetype(
        "tent",
        "private_room",
        "camping",
        ("desert", "cabin", "heritage"),
        (2500, 9000),
        (2, 4),
        (1, 2),
        ("Desert Camp", "Dune Tent", "Luxury Desert Tent", "Sunset Camp"),
        ("on the dunes", "with a bonfire evening", "with folk music at night", "under the stars"),
        ("hot_water", "bonfire"),
        ("wifi", "breakfast", "ac", "garden_view", "free_parking"),
        "A comfortable tent camp where dinner comes with folk music and a sky full of stars.",
    ),
    "river_stay": Archetype(
        "guest_house",
        "private_room",
        "amazing_views",
        ("spiritual", "hills", "interior"),
        (1800, 6000),
        (2, 4),
        (1, 2),
        ("Riverside Guesthouse", "Ganga View Room", "Ghat-side Stay", "Yoga Retreat Room"),
        ("with river views", "with a morning yoga deck", "near the ghats", "with a rooftop"),
        ("wifi", "hot_water"),
        ("breakfast", "balcony", "garden", "ac", "mountain_view", "workspace"),
        "A calm, simple stay for early risers, with chanting and river light in the mornings.",
    ),
    "heritage_haveli": Archetype(
        "heritage_home",
        "entire",
        "heritage",
        ("heritage", "interior", "desert"),
        (6000, 32000),
        (4, 10),
        (2, 5),
        ("Heritage Haveli", "Restored Haveli", "Courtyard Haveli", "Old City Haveli"),
        ("with a courtyard", "with painted walls", "with rooftop dining", "with carved balconies"),
        ("wifi", "ac", "hot_water", "breakfast"),
        ("balcony", "garden", "free_parking", "kitchen", "tv", "pool"),
        "A restored family haveli with painted walls, carved doorways and a courtyard that stays cool all day.",
    ),
    "palace_suite": Archetype(
        "heritage_home",
        "private_room",
        "mansions",
        ("heritage", "interior", "pool"),
        (12000, 45000),
        (2, 4),
        (1, 2),
        ("Palace Suite", "Royal Suite", "Maharani Suite", "Durbar Suite"),
        (
            "with a lake view",
            "with a four-poster bed",
            "with a private terrace",
            "with butler service",
        ),
        ("wifi", "ac", "hot_water", "breakfast"),
        ("pool", "balcony", "garden", "gym", "hair_dryer", "iron"),
        "A suite in a former royal residence, with antique furniture and a terrace made for sunsets.",
    ),
    "lake_palace_view": Archetype(
        "villa",
        "entire",
        "lakefront",
        ("heritage", "interior", "pool"),
        (8000, 26000),
        (4, 8),
        (2, 4),
        ("Lakeview Villa", "Lakeside Residence", "Sunset Lake Villa", "Pichola Terrace Home"),
        ("with a lake view", "with a rooftop terrace", "with a private jetty", "with a sun deck"),
        ("wifi", "ac", "hot_water", "lake_access"),
        ("balcony", "breakfast", "kitchen", "free_parking", "pool", "tv"),
        "A lakeside home where every window frames the water and the old city beyond it.",
    ),
    "houseboat": Archetype(
        "houseboat",
        "entire",
        "houseboats",
        ("backwaters", "interior", "estate"),
        (6500, 16000),
        (2, 6),
        (1, 3),
        ("Kettuvallam Houseboat", "Backwater Houseboat", "Luxury Houseboat", "Sunset Houseboat"),
        (
            "with a crew and chef",
            "with a sun deck",
            "with an air-conditioned bedroom",
            "cruising the backwaters",
        ),
        ("hot_water", "breakfast", "ac"),
        ("wifi", "balcony", "tv", "garden_view"),
        "A traditional rice-barge houseboat with a cook on board and a slow drift through the canals.",
    ),
    "backwater_homestay": Archetype(
        "house",
        "private_room",
        "tropical",
        ("backwaters", "estate", "interior"),
        (1800, 4500),
        (2, 4),
        (1, 2),
        ("Backwater Homestay", "Canalside Home", "Paddy View Homestay", "Coconut Lagoon Room"),
        ("with home-cooked Kerala meals", "by the canal", "with a canoe", "in a coconut grove"),
        ("wifi", "hot_water", "breakfast"),
        ("ac", "garden", "balcony", "free_parking", "garden_view"),
        "A friendly family homestay with fish curry for lunch and a canoe at the jetty.",
    ),
    "plantation_bungalow": Archetype(
        "house",
        "entire",
        "farms",
        ("estate", "hills", "interior"),
        (5500, 16000),
        (4, 8),
        (2, 4),
        ("Plantation Bungalow", "Estate Bungalow", "Coffee Planter's Home", "Tea Estate Villa"),
        (
            "inside a working estate",
            "with a wraparound veranda",
            "with a bonfire pit",
            "with a private cook",
        ),
        ("wifi", "hot_water", "kitchen", "garden"),
        ("bonfire", "mountain_view", "free_parking", "breakfast", "heating", "bbq_grill", "tv"),
        "A planter's bungalow set inside a working estate, with estate walks and filter coffee on the veranda.",
    ),
    "farm_stay": Archetype(
        "farm_stay",
        "entire",
        "farms",
        ("estate", "hills", "cabin"),
        (3500, 9000),
        (2, 6),
        (1, 3),
        ("Farm Stay", "Orchard Farmhouse", "Spice Farm Cottage", "Organic Farm Retreat"),
        (
            "with farm-to-table meals",
            "among spice gardens",
            "with guided farm walks",
            "with fresh produce daily",
        ),
        ("wifi", "hot_water", "garden"),
        ("breakfast", "bonfire", "kitchen", "free_parking", "garden_view", "balcony"),
        "A working farm where meals come straight from the garden and the day starts with birdsong.",
    ),
    "french_quarter_house": Archetype(
        "house",
        "entire",
        "design",
        ("beach", "heritage", "interior"),
        (5500, 18000),
        (2, 6),
        (1, 3),
        (
            "French Quarter House",
            "Ochre Courtyard Home",
            "Colonial Townhouse",
            "Boulevard Residence",
        ),
        ("with a courtyard", "in the French Quarter", "with a plunge pool", "with a rooftop"),
        ("wifi", "ac", "hot_water", "kitchen"),
        ("pool", "balcony", "garden", "breakfast", "workspace", "free_parking"),
        "A pastel townhouse on a quiet boulevard, with shutters, a courtyard and bicycles to borrow.",
    ),
}

ADJECTIVES = (
    "Sunlit",
    "Serene",
    "Hidden",
    "Breezy",
    "Whitewashed",
    "Rustic",
    "Tranquil",
    "Cosy",
    "Charming",
    "Peaceful",
    "Secluded",
    "Elegant",
    "Quaint",
    "Bright",
    "Verdant",
    "Golden",
)

AMENITY_SENTENCES = {
    "pool": "You have a private pool to yourselves.",
    "kitchen": "The kitchen is fully equipped if you feel like cooking.",
    "breakfast": "A home-style breakfast is included every morning.",
    "bonfire": "In the evenings there is a bonfire pit to gather around.",
    "heating": "Heating keeps the nights comfortable.",
    "ac": "The bedrooms are air-conditioned.",
    "workspace": "There is a proper desk and fast wifi if you need to work.",
    "beach_access": "The beach is an easy walk away.",
}

CLOSERS = (
    "Your host lives nearby and is happy to share tips on where to eat and what to see.",
    "Self check-in is easy, and your host is a message away if you need anything.",
    "Local recommendations are waiting on the table when you arrive.",
    "Your host can arrange airport pickups, local guides and cooking sessions.",
)

HOUSE_RULES = (
    "Check-in after the stated time. Quiet hours from 10 pm.",
    "No parties or events. Please respect the neighbours.",
    "Smoking only in outdoor areas. Please keep the property clean.",
    "Guests are responsible for any damage during their stay.",
)

REVIEW_COMMENTS = {
    5: (
        "Everything was exactly as described and the host went out of their way to help. We would stay again in a heartbeat.",
        "Spotless, peaceful and beautifully set up. The photos do not do the place justice.",
        "A wonderful stay. Great location, comfortable beds and a lovely host. Highly recommended.",
        "We loved every minute. The views were stunning and the little touches made it feel like home.",
        "Perfect for our family trip. Quick replies from the host and so many thoughtful extras.",
        "One of the best stays we have had in India. Warm hospitality and an unbeatable setting.",
        "Great value and a really relaxing atmosphere. We did not want to leave.",
        "Easy check-in, a comfortable bed and delicious local food suggestions from the host.",
    ),
    4: (
        "A lovely place with a great host. A couple of small things could be better, but overall we were very happy.",
        "Good location and comfortable. The wifi was a bit slow but everything else was great.",
        "Nice stay and good value. The place is a little older than the photos suggest but very clean.",
        "We enjoyed our time here. Friendly host and a peaceful setting. Would come back.",
    ),
    3: (
        "Decent stay for the price. The location is good, but the room needed a bit more maintenance.",
        "Average experience. The host was helpful but the place was noisier than expected.",
    ),
    2: ("The place was fine but not as described. Cleanliness could be better.",),
}
