"""The 20 Indian destinations the demo covers, with the kinds of stays each one offers."""

from dataclasses import dataclass


@dataclass(frozen=True)
class Destination:
    city: str
    state: str
    latitude: float
    longitude: float
    pin: str
    host: str  # key in people.PEOPLE
    stays: tuple[str, ...]  # archetype keys from content.ARCHETYPES, one per listing
    streets: tuple[str, ...]
    highlights: tuple[str, ...]  # local colour used in descriptions


DESTINATIONS = [
    Destination(
        "Anjuna",
        "Goa",
        15.5736,
        73.7410,
        "403509",
        "aarav",
        ("beach_villa", "beach_villa", "beach_cottage", "design_loft"),
        ("Beach Road", "Vagator Hill Road", "Mazal Waddo"),
        (
            "a short walk from Anjuna's flea market and beach shacks",
            "ten minutes from the cliffs of Vagator",
        ),
    ),
    Destination(
        "Palolem",
        "Goa",
        15.0100,
        74.0232,
        "403702",
        "aarav",
        ("beach_cottage", "beach_cottage", "cabin_stay"),
        ("Palolem Beach Road", "Colom Road"),
        ("steps from the crescent bay of Palolem", "a kayak ride away from Butterfly Beach"),
    ),
    Destination(
        "Mumbai",
        "Maharashtra",
        19.0760,
        72.8777,
        "400050",
        "aarav",
        ("city_apartment", "city_apartment", "design_loft"),
        ("Carter Road", "Linking Road", "Hill Road"),
        ("a walk from the Bandra seafront", "close to Marine Drive and the Gateway of India"),
    ),
    Destination(
        "Manali",
        "Himachal Pradesh",
        32.2432,
        77.1892,
        "175131",
        "rohan",
        ("hill_cottage", "cabin_stay", "cabin_stay", "treehouse"),
        ("Old Manali Road", "Vashisht Road", "Naggar Road"),
        (
            "above the Beas river with deodar forest all around",
            "a few minutes from Old Manali's cafes",
        ),
    ),
    Destination(
        "Shimla",
        "Himachal Pradesh",
        31.1048,
        77.1734,
        "171001",
        "rohan",
        ("hill_cottage", "hill_cottage", "colonial_house"),
        ("Mall Road", "Chhota Shimla", "Mashobra Road"),
        (
            "with deodar-lined walks and views of the ridge",
            "close to the Mall and the toy-train station",
        ),
    ),
    Destination(
        "Leh",
        "Ladakh",
        34.1526,
        77.5771,
        "194101",
        "rohan",
        ("ladakh_guesthouse", "ladakh_guesthouse", "desert_camp"),
        ("Changspa Road", "Fort Road"),
        (
            "under the Stok Kangri range at 3,500 metres",
            "a short drive from Thiksey and Shey monasteries",
        ),
    ),
    Destination(
        "Rishikesh",
        "Uttarakhand",
        30.0869,
        78.2676,
        "249304",
        "meera",
        ("river_stay", "river_stay", "cabin_stay"),
        ("Tapovan Road", "Laxman Jhula Road"),
        (
            "a short walk from the Ganga ghats and yoga shalas",
            "with the sound of the river in the background",
        ),
    ),
    Destination(
        "Varanasi",
        "Uttar Pradesh",
        25.3176,
        82.9739,
        "221001",
        "meera",
        ("river_stay", "heritage_haveli"),
        ("Assi Ghat Road", "Dashashwamedh Road"),
        (
            "minutes from the evening aarti on the ghats",
            "in the old city lanes that lead to the Ganga",
        ),
    ),
    Destination(
        "Darjeeling",
        "West Bengal",
        27.0360,
        88.2627,
        "734101",
        "meera",
        ("colonial_house", "hill_cottage"),
        ("Mall Road", "Tenzing Norgay Road"),
        ("with sunrise views of Kanchenjunga on clear mornings", "surrounded by tea gardens"),
    ),
    Destination(
        "Jaipur",
        "Rajasthan",
        26.9124,
        75.7873,
        "302001",
        "vikram",
        ("heritage_haveli", "heritage_haveli", "palace_suite", "design_loft"),
        ("Civil Lines", "Bani Park", "Amer Road"),
        (
            "a short ride from Amber Fort and the Pink City bazaars",
            "close to Hawa Mahal and Johari Bazaar",
        ),
    ),
    Destination(
        "Udaipur",
        "Rajasthan",
        24.5854,
        73.7125,
        "313001",
        "vikram",
        ("lake_palace_view", "palace_suite", "heritage_haveli"),
        ("Lake Pichola Road", "Gangaur Ghat Marg"),
        ("with views across Lake Pichola to the City Palace", "a boat ride from Jag Mandir"),
    ),
    Destination(
        "Jaisalmer",
        "Rajasthan",
        26.9157,
        70.9083,
        "345001",
        "vikram",
        ("desert_camp", "desert_camp", "heritage_haveli"),
        ("Gandhi Chowk", "Sam Road"),
        ("a camel ride from the Sam sand dunes", "within sight of the golden fort"),
    ),
    Destination(
        "Alleppey",
        "Kerala",
        9.4981,
        76.3388,
        "688001",
        "priya",
        ("houseboat", "houseboat", "houseboat", "backwater_homestay"),
        ("Punnamada Road", "Finishing Point Road"),
        ("gliding through the Vembanad backwaters", "with coconut groves along the canal"),
    ),
    Destination(
        "Kochi",
        "Kerala",
        9.9312,
        76.2673,
        "682001",
        "priya",
        ("heritage_haveli", "backwater_homestay"),
        ("Princess Street", "Fort Kochi Beach Road"),
        ("a stroll from the Chinese fishing nets", "in the lanes of Fort Kochi"),
    ),
    Destination(
        "Munnar",
        "Kerala",
        10.0889,
        77.0595,
        "685612",
        "priya",
        ("plantation_bungalow", "hill_cottage", "treehouse"),
        ("Top Station Road", "Devikulam Road"),
        ("among rolling tea plantations", "above the mist line with views of the valley"),
    ),
    Destination(
        "Coorg",
        "Karnataka",
        12.3375,
        75.8069,
        "571201",
        "ananya",
        ("plantation_bungalow", "plantation_bungalow", "farm_stay"),
        ("Madikeri Road", "Virajpet Road"),
        ("inside a working coffee estate", "close to Abbey Falls and the Dubare elephant camp"),
    ),
    Destination(
        "Bengaluru",
        "Karnataka",
        12.9716,
        77.5946,
        "560038",
        "ananya",
        ("city_apartment", "design_loft"),
        ("Indiranagar 12th Main", "Koramangala 5th Block"),
        (
            "walking distance to Indiranagar's cafes and microbreweries",
            "near Cubbon Park and the metro",
        ),
    ),
    Destination(
        "Ooty",
        "Tamil Nadu",
        11.4102,
        76.6950,
        "643001",
        "ananya",
        ("colonial_house", "hill_cottage"),
        ("Charing Cross Road", "Kotagiri Road"),
        ("a short walk from Ooty Lake", "with Nilgiri hills and eucalyptus all around"),
    ),
    Destination(
        "Pondicherry",
        "Puducherry",
        11.9416,
        79.8083,
        "605001",
        "ananya",
        ("french_quarter_house", "french_quarter_house", "beach_cottage"),
        ("Rue Suffren", "Rue Romain Rolland"),
        ("in the French Quarter, steps from the Promenade", "close to Auroville and the sea"),
    ),
    Destination(
        "Gokarna",
        "Karnataka",
        14.5479,
        74.3188,
        "581326",
        "ananya",
        ("beach_cottage", "cabin_stay"),
        ("Om Beach Road", "Kudle Beach Trail"),
        ("above Kudle Beach on a quiet cliff path", "a trek away from Om Beach"),
    ),
]
