/** Pages that exist on the original site but are placeholders here, keyed by their original path. */
export const INFO_PAGES: Record<string, { title: string; blurb?: string }> = {
  "help/home": { title: "Help Centre", blurb: "Guides and answers for guests and hosts." },
  "help/contact-us": { title: "Contact us" },
  "help/responsible-hosting": { title: "Responsible hosting" },
  aircover: { title: "AirCover", blurb: "Protection for every booking." },
  "aircover-for-hosts": { title: "AirCover for Hosts" },
  "against-discrimination": { title: "Anti-discrimination" },
  accessibility: { title: "Accessibility" },
  neighbors: { title: "Neighbourhood support" },
  resources: { title: "Hosting resources" },
  "e/intro-to-hosting": { title: "Introduction to hosting" },
  "host/homes": { title: "Airbnb your home", blurb: "Create a listing and start hosting." },
  "host/experiences": { title: "Host an experience" },
  "host/services": { title: "Offer a service" },
  "host/co-hosts": { title: "Find a co-host" },
  refer: { title: "Refer a host" },
  release: { title: "New features" },
  "press/news": { title: "Newsroom" },
  careers: { title: "Careers" },
  terms: { title: "Terms of Service" },
  "terms/privacy_policy": { title: "Privacy Policy" },
  "about/company-details": { title: "Company details" },
  "gift-cards": { title: "Gift cards" },
  "t5/Community-Center/ct-p/community-center": { title: "Community forum" },
};
